services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/html/storage
    depends_on:
      - app

  app:
    image: vethsothi/social-media-app:latest
    container_name: social-media-app
    expose:
      - "9000"
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_DATABASE=social_media
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: social-media-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_media
